apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dicom-fuzzer

resources:
  - namespace.yaml
  - rbac.yaml
  - redis.yaml
  - coordinator.yaml
  - worker.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: dicom-fuzzer
  app.kubernetes.io/version: "1.5.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/dashtid/dicom-fuzzer
    newTag: latest
